EVE-21 - PULL REQUEST - FileServer and Attachment Service
akademia-envelo-3/MELO-back pull request #130
Opened 2023-01-25 13:00 UTC by iLoveBingo

2023-01-26 13:47 UTC, Albi7331 commented
Must have:
Niech atachment zawiera link do zasobu, który do czegoś prowadzi.
Nice to have:
Niech link do zasobu nie wywołuje pobierania tylko, wyświetla obrazek

2023-01-26 13:48 UTC, Albi7331 requested changes
Must have:
Niech atachment zawiera link do zasobu, który do czegoś prowadzi.
Nice to have:
Niech link do zasobu nie wywołuje pobierania tylko, wyświetla obrazek

2023-01-30 14:51 UTC, Albi7331 approved these changes
Przeszło rygorystyczne testy

2023-01-30 14:53 UTC, rafalfuz approved these changes

2023-01-30 14:54 UTC, przemyslawmroczek approved these changes
DZIALA?
fix: dziala juz serio
fix: dziala dajcie mi juz spoko
dziala fest

Wygląda legit

2023-01-30 14:55 UTC, iLoveBingo commented
Nie da się zrobić bardziej rygorystycznych godzinnych testów niż @Albi7331. Pozdrawiam cieplutko.

2023-01-30 14:55 UTC, merged