UNI-06 join Unit
akademia-envelo-3/MELO-back pull request #161
Opened 2023-02-02 11:56 UTC by Basia413

2023-02-02 12:54 UTC, MarekGFx approved these changes
przy poprawnym zapisywaniu mógłby być komunikat że "emploj poprawnie dodany lub cuś" zamiast samego true
A tak To LGTM LGBT LGBTMQW+

2023-02-03 12:23 UTC, Albi7331 commented
Ścieżka /units/{id} powinna wskazywać id unitu, a nie employee

2023-02-03 12:24 UTC, Albi7331 requested changes
Ścieżka /units/{id} powinna wskazywać id unitu, a nie employee

2023-02-03 12:37 UTC, Albi7331 approved these changes

2023-02-03 12:42 UTC, merged