feat EVE-13: crate event fixed whith correct increment hashtag
akademia-envelo-3/MELO-back pull request #170
Opened 2023-02-08 10:24 UTC by MarekGFx

2023-02-08 14:45 UTC, Basia413 commented on src/main/java/pl/envelo/melo/domain/hashtag/HashtagService.java
> +            System.out.println("insertNewHashtag if does not exist: " + hashtag.getContent());
sout do wyrzucenia

2023-02-08 14:45 UTC, Basia413 commented on src/main/java/pl/envelo/melo/domain/hashtag/HashtagService.java
> +            System.out.println("incrementHashtagGlobalCount: " + hashtag.getContent());
i tu

2023-02-08 14:46 UTC, Basia413 reviewed
Można dodać wydarzenie z datą, która się odbyła

2023-02-13 09:56 UTC, Albi7331 commented on src/main/java/pl/envelo/melo/validators/EventValidator.java
> +            if (eventDto.getEventType().name().contains("LIMITED")) {
Poprawić na startsWith

2023-02-13 09:57 UTC, Albi7331 commented on src/main/java/pl/envelo/melo/domain/event/EventService.java
> +                return ResponseEntity.status(400).body("Event with limited eventType must have higher memberLimit than 0.");
Redundantne sprawdzanie

2023-02-13 09:59 UTC, Albi7331 requested changes
Poprawić metody w EventService i EventValidator

2023-02-13 10:08 UTC, przemyslawmroczek commented
- Hashtag się nie tworzy w bazie po utworzeniu eventu
- Po utworzeniu eventu wydaje mi się że przydałoby sie wyrzucać chociaż jego id żeby front wiedział co pobrać

2023-02-13 10:13 UTC, Albi7331 commented on src/main/java/pl/envelo/melo/domain/event/EventService.java
> +                Map<String, String> validationResult = eventValidator.validateToCreateEvent(newEventDto);
To sprawdzanie powinno być wykonane przed zapisaniem czegokolwiek. W tym przypadku lokacja jest zapisywana mimo nie powodzenia dodania eventu.

2023-02-13 10:13 UTC, przemyslawmroczek requested changes
- Hashtag się nie tworzy w bazie po utworzeniu eventu
- Po utworzeniu eventu wydaje mi się że przydałoby sie wyrzucać chociaż jego id żeby front wiedział co pobrać

2023-02-13 10:19 UTC, Albi7331 requested changes
Gdzie jest dodawanie hasztagów???

2023-02-14 15:26 UTC, Albi7331 approved these changes

2023-02-14 15:27 UTC, przemyslawmroczek approved these changes
Jestem dumny i zadowolony z efektu :>

2023-02-14 15:42 UTC, merged