feat AUTH-05: Adjusted app functionalities to retrieve user from principal token
akademia-envelo-3/MELO-back pull request #174
Opened 2023-02-13 14:41 UTC by Albi7331

2023-02-14 10:08 UTC, przemyslawmroczek requested changes
- java.lang.IllegalStateException: Ambiguous handler methods mapped for '/api/v1/units/1' -> patch /v1/units/{unitId}  - przy próbie podania unitId/newEmployeeId o wartości których nie ma w bazie.//w sumie i przy podaniu poprawnych danych; i przy próbie edycji unitu
- patch /v1/units/{unitId} i /v1/units/{id}/owner - dla admina i dla employee robią dokładnie to samo i przyjmują unitId i newOwnerEmployeeId
- get /v1/units/{id} zmienić nazwe w swaggerze bo jest myląca "retrieve list of units". tak samo w get /v1/units/{unitId}/join Add employee -> join unit.... /v1/units/{unitId}/members -> just quit/disjoin

Events:
- /v1/events/{id}/comments przyjmuje arg0 i nie dziala dodawanie komentarza - "Failed to convert 'null' with value: '{id}'"
- post vote in Poll przyjmuje {emp-id} i mozna glosowac jako dowolny employee
- patch /v1/events/{id}/organizer nie przyjmuje id nowego organizera
- /v1/events/{event-id}/polls/{poll-id} przyjmuje employee-id zamiast principal

2023-02-14 13:56 UTC, Basia413 approved these changes

2023-02-16 10:04 UTC, przemyslawmroczek reviewed
- /v1/units/{unitId}/owner - nie zmienia ownera mimo ResponseStatus = 200
- /v1/users/{id}/owned-units - usunac param id
- v1/events/{id}/comments - arg0
- v1/events/{id}/organizer - 400:"You are event organizer already", mimo że podawany jest inny Employee

2023-02-16 10:52 UTC, przemyslawmroczek approved these changes

2023-02-16 11:41 UTC, merged