Eve 26 - edit event
akademia-envelo-3/MELO-back pull request #175
Opened 2023-02-14 12:54 UTC by Basia413

2023-02-14 14:02 UTC, Albi7331 requested changes
Minor:
Nullpointerexception podczas gdy próbuję usunąć z eventu kategorię której nie ma. 
Major:
Data początku i końca się nie aktualizuje

2023-02-14 14:06 UTC, Albi7331 commented
Major:
Mogę dodać więcej niż 10 załączników

2023-02-15 08:51 UTC, iLoveBingo commented
Poczytaj o JsonParser i JsonPatch. Bardziej skondensowane i dużo mniej linijek kodu. BeanUtils też warto looknąć, bo ułatwia mapowanie i przy interakcji z bazą/dto samo wychwyci nulle co ci zaoszczędzi kodu na if-ach a szczególnie tam, gdzie się zagnieżdżają.

2023-02-20 11:00 UTC, Albi7331 commented
Serwer wyrzuca kod 500 w przypadku próby dodania pracownika nie istniejącego w bazie. Aplikacja nie aktualizuje dat. Aplikacja nie usuwa hashtagów.

2023-02-20 14:29 UTC, Albi7331 commented
W przypadku podania w mapie "adds" istniejącego już w evencie hashtaga, jego licznik się inkrementuje.

2023-02-20 15:41 UTC, Albi7331 approved these changes

2023-02-21 14:43 UTC, przemyslawmroczek approved these changes

2023-02-21 14:58 UTC, merged