feat EVE-28: set hahstag flag - admin functionality
akademia-envelo-3/MELO-back pull request #196
Opened 2023-02-17 10:53 UTC by MarekGFx

działa jak złoto

2023-02-20 15:07 UTC, przemyslawmroczek requested changes
```
"title": "Bad Request",
  "status": 400,
  "detail": "Required parameter 'hide' is not present.",
```
  
  brak nazwy przy request param
![image](https://user-images.githubusercontent.com/49682737/220142802-058a8801-33db-45ba-9adf-ff24c0c1c7d1.png)

2023-02-21 10:12 UTC, Basia413 approved these changes

2023-02-21 10:27 UTC, Albi7331 commented
Przy mergowaniu:
- dostosować endpoint do stanu na developie

2023-02-21 10:27 UTC, Albi7331 approved these changes

2023-02-21 12:08 UTC, przemyslawmroczek approved these changes

2023-02-21 12:09 UTC, merged