Int 20 - Refactor
akademia-envelo-3/MELO-back pull request #201
Opened 2023-02-20 15:38 UTC by iLoveBingo

2023-02-21 10:13 UTC, Albi7331 requested changes
Aplikacja wyrzuca NullPointerException w przypadku próby dodania eventu limitowanego i podania wartości null jako parametr memberLimit. Należy dodać walidację w linijce 31 i 60 w klasie EventValidator.
```java
if (Objects.isNull(eventDto.getMemberLimit()) || eventDto.getMemberLimit() < 2) 
```

2023-02-21 14:37 UTC, iLoveBingo commented
Poprawiono wykryte uchybienia w zakresie bezpieczeństwa walidacji klasy operującej na obiektach typu Event.

2023-02-23 14:54 UTC, Albi7331 approved these changes

2023-02-24 08:17 UTC, Basia413 approved these changes

2023-02-27 14:03 UTC, merged